CREATE TABLE `Provider` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `image` varchar(45) DEFAULT NULL,
  `url` varchar(45) DEFAULT NULL,
  `phone` varchar(45) DEFAULT NULL,
  `address1` varchar(45) DEFAULT NULL,
  `address2` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `state` varchar(45) DEFAULT NULL,
  `postal_code` varchar(45) DEFAULT NULL,
  `contact_name` varchar(45) DEFAULT NULL,
  `contact_email` varchar(45) DEFAULT NULL,
  `contact_phone` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1007 DEFAULT CHARSET=latin1;
INSERT INTO `powerup`.`Provider`
(`id`,
`name`,
`description`,
`type`,
`image`,
`url`,
`phone`,
`address1`,
`address2`,
`city`,
`state`,
`postal_code`,
`contact_name`,
`contact_email`,
`contact_phone`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{type: }>,
<{image: }>,
<{url: }>,
<{phone: }>,
<{address1: }>,
<{address2: }>,
<{city: }>,
<{state: }>,
<{postal_code: }>,
<{contact_name: }>,
<{contact_email: }>,
<{contact_phone: }>);

CREATE TABLE `Offering` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `provider_id` int(11) DEFAULT NULL,
  `provider_name` varchar(45) DEFAULT NULL,
  `name` varchar(45) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `category` varchar(45) DEFAULT NULL COMMENT 'MUSIC, DANCE, ART, MATH, LANGUGAGE, SPORTS, GYM,     what else ?',
  `image1` blob,
  `image2` blob,
  `image3` blob,
  `video_url` varchar(45) DEFAULT NULL,
  `start_date` varchar(20) DEFAULT NULL,
  `end_date` varchar(20) DEFAULT NULL,
  `duration` varchar(45) DEFAULT NULL COMMENT '30 min, 1 hr, 2 hrs, 1 day, 2 days etc.',
  `days` varchar(100) DEFAULT NULL COMMENT 'Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
  `schedule` varchar(100) DEFAULT NULL COMMENT 'de-normalized schedule',
  `age` varchar(45) DEFAULT NULL,
  `grade` varchar(45) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `price_unit` varchar(45) DEFAULT NULL COMMENT 'Price per class or whole year etc',
  `credt_card_accepted` varchar(10) DEFAULT NULL COMMENT 'Yes, No',
  `enable_review` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1008 DEFAULT CHARSET=latin1;
INSERT INTO `powerup`.`Offering`
(`id`,
`provider_id`,
`provider_name`,
`name`,
`description`,
`category`,
`image1`,
`image2`,
`image3`,
`video_url`,
`start_date`,
`end_date`,
`duration`,
`days`,
`schedule`,
`age`,
`grade`,
`price`,
`price_unit`,
`credt_card_accepted`,
`enable_review`)
VALUES
(<{id: }>,
<{provider_id: }>,
<{provider_name: }>,
<{name: }>,
<{description: }>,
<{category: }>,
<{image1: }>,
<{image2: }>,
<{image3: }>,
<{video_url: }>,
<{start_date: }>,
<{end_date: }>,
<{duration: }>,
<{days: }>,
<{schedule: }>,
<{age: }>,
<{grade: }>,
<{price: }>,
<{price_unit: }>,
<{credt_card_accepted: }>,
<{enable_review: }>);
CREATE TABLE `Offering_Schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `offering_id` varchar(45) DEFAULT NULL,
  `start_date` varchar(45) DEFAULT NULL,
  `end_date` varchar(45) DEFAULT NULL,
  `start_time` varchar(45) DEFAULT NULL,
  `end_time` varchar(45) DEFAULT NULL,
  `days` varchar(45) DEFAULT NULL,
  `no_of_seats` int(11) DEFAULT NULL,
  `available_seats` int(11) DEFAULT NULL,
  `sunday` varchar(45) DEFAULT NULL,
  `monday` varchar(45) DEFAULT NULL,
  `tuesday` varchar(45) DEFAULT NULL,
  `wednesday` varchar(45) DEFAULT NULL,
  `thursday` varchar(45) DEFAULT NULL,
  `friday` varchar(45) DEFAULT NULL,
  `saturday` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1011 DEFAULT CHARSET=latin1;
INSERT INTO `powerup`.`Offering_Schedule`
(`id`,
`offering_id`,
`start_date`,
`end_date`,
`start_time`,
`end_time`,
`days`,
`no_of_seats`,
`available_seats`,
`sunday`,
`monday`,
`tuesday`,
`wednesday`,
`thursday`,
`friday`,
`saturday`)
VALUES
(<{id: }>,
<{offering_id: }>,
<{start_date: }>,
<{end_date: }>,
<{start_time: }>,
<{end_time: }>,
<{days: }>,
<{no_of_seats: }>,
<{available_seats: }>,
<{sunday: }>,
<{monday: }>,
<{tuesday: }>,
<{wednesday: }>,
<{thursday: }>,
<{friday: }>,
<{saturday: }>);
CREATE TABLE `Enrollment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `provider_id` int(11) DEFAULT NULL,
  `prvider_name` varchar(45) DEFAULT NULL,
  `offering_id` int(11) DEFAULT NULL,
  `offering_name` varchar(45) DEFAULT NULL,
  `offering_schedule_id` int(11) DEFAULT NULL,
  `student_contact_id` int(11) DEFAULT NULL,
  `student_contact_name` varchar(45) DEFAULT NULL,
  `parent_contact_id` int(11) DEFAULT NULL,
  `parent_contact_name` varchar(45) DEFAULT NULL,
  `start_date` varchar(45) DEFAULT NULL,
  `offering_days` varchar(45) DEFAULT NULL,
  `start_offering_time` varchar(45) DEFAULT NULL,
  `end_offering_time` varchar(45) DEFAULT NULL,
  `payment_mode` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=latin1;
INSERT INTO `powerup`.`Enrollment`
(`id`,
`provider_id`,
`prvider_name`,
`offering_id`,
`offering_name`,
`offering_schedule_id`,
`student_contact_id`,
`student_contact_name`,
`parent_contact_id`,
`parent_contact_name`,
`start_date`,
`offering_days`,
`start_offering_time`,
`end_offering_time`,
`payment_mode`)
VALUES
(<{id: }>,
<{provider_id: }>,
<{prvider_name: }>,
<{offering_id: }>,
<{offering_name: }>,
<{offering_schedule_id: }>,
<{student_contact_id: }>,
<{student_contact_name: }>,
<{parent_contact_id: }>,
<{parent_contact_name: }>,
<{start_date: }>,
<{offering_days: }>,
<{start_offering_time: }>,
<{end_offering_time: }>,
<{payment_mode: }>);

