/*
-- Query: SELECT * FROM powerup.Offering
LIMIT 0, 1000

-- Date: 2014-10-13 19:13
*/
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1001,1005,'Sutton Swim School ','Swim Classes - General','\nSwim for Babies, Beginner, Intermediate, Strokes','Waterpolo',?,?,?,NULL,'11/01/2014','12/31/2014','30 mins','daily',NULL,'All',NULL,37.00,'per class','No','Yes');
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1002,1005,'Sutton Swim School ','Swim Classes for Babies','\nSwim for Babies, Beginner, Intermediate, Strokes','\nSwimming Lessons/Schools',?,?,?,NULL,'11/15/2014','12/31/2014','30 mins','daily',NULL,'6 - 11 years',NULL,40.00,'per class','No','Yes');
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1003,1005,'Sutton Swim School ','Swim Classes for Intermediate','\nSwim for Babies, Beginner, Intermediate, Strokes','\nSwimming Lessons/Schools',?,?,?,NULL,'12/01/2014','01/30/2015','45 mins','daily',NULL,'11 - 18 years',NULL,500.00,'for session','No','Yes');
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1004,1005,'Sutton Swim School ','Swim Classes for Adults','\nSwim for Babies, Beginner, Intermediate, Strokes','\nSwimming Lessons/Schools',?,?,?,NULL,'12/15/2014','01/30/2015','1 hr','daily',NULL,'18+ years',NULL,2000.00,'for annual enrollment','No','Yes');
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1005,NULL,NULL,'test',NULL,'ttt',NULL,NULL,NULL,NULL,'','','',NULL,NULL,'',NULL,100.00,'per class',NULL,NULL);
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1006,NULL,NULL,'Another test',NULL,'Karte',NULL,NULL,NULL,NULL,'','','',NULL,NULL,'6 years',NULL,2000.00,'per annual',NULL,NULL);
INSERT INTO `Offering` (`id`,`provider_id`,`provider_name`,`name`,`description`,`category`,`image1`,`image2`,`image3`,`video_url`,`start_date`,`end_date`,`duration`,`days`,`schedule`,`age`,`grade`,`price`,`price_unit`,`credt_card_accepted`,`enable_review`) VALUES (1007,NULL,NULL,'Test Swimming',NULL,'',NULL,NULL,NULL,NULL,'','','',NULL,NULL,'10',NULL,150.00,'per class',NULL,NULL);
