/*
-- Query: SELECT * FROM powerup.Offering_Schedule
LIMIT 0, 1000

-- Date: 2014-10-13 19:14
*/
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1001,'1001','11/01/2014','01/01/2015','4:00PM','4:30PM','Sunday, Monday, Thursday, Friday',20,10,'','','disabled','disabled','','','disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1002,'1001','11/01/2014','01/01/2015','4:30PM','5:00PM','Sunday, Monday, Thursday, Friday',15,2,NULL,NULL,'disabled','disabled',NULL,NULL,'disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1003,'1001','11/01/2014','01/01/2015','5:00PM','5:30PM','Sunday, Monday, Thursday, Friday',18,11,NULL,NULL,'disabled','disabled',NULL,NULL,'disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1004,'1001','11/01/2014','01/01/2015','5:30PM','6:00PM','Sunday, Monday, Thursday, Friday',20,5,'','','disabled','disabled','disabled',NULL,'disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1005,'1001','11/01/2014','01/01/2015','6:00PM','6:30PM','Sunday, Monday, Thursday, Friday',15,10,'','',NULL,'disabled',NULL,'disabled`','disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1006,'1001','11/01/2014','01/01/2015','6:30PM','7:00PM','Sunday, Monday, Thursday, Friday',20,1,'','',NULL,NULL,NULL,NULL,'disabled');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1007,'1001','11/01/2014','01/01/2015','7:00AM','7:30AM','Tuesday',10,5,NULL,NULL,'',NULL,'disabled','disabled',NULL);
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1008,'1001','11/01/2014','01/01/2015','7:30PM','8:00PM','Tuesday',10,2,NULL,NULL,'','disabled',NULL,'disabled',NULL);
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1009,'1001','11/01/2014','01/01/2015','9:00AM','9:30AM','Saturday',25,2,NULL,NULL,NULL,NULL,'disabled','disabled','');
INSERT INTO `Offering_Schedule` (`id`,`offering_id`,`start_date`,`end_date`,`start_time`,`end_time`,`days`,`no_of_seats`,`available_seats`,`sunday`,`monday`,`tuesday`,`wednesday`,`thursday`,`friday`,`saturday`) VALUES (1010,'1001','11/01/2014','01/01/2015','9:30PM','10:30AM','Sunday, Monday, Thursday, Friday',20,3,'','disabled','disabled','disabled',NULL,'',NULL);
